// pages/index.js
import styled from 'styled-components'
import Layout from '../components/Layout'
import Link from 'next/link'

const Hero = styled.section`
  text-align: center;
  padding: 6rem 1rem;
`

const Title = styled.h1`
  font-size: 3rem;
  color: #222;
  margin-bottom: 1rem;
`

const Subtitle = styled.p`
  font-size: 1.25rem;
  color: #666;
  max-width: 32rem;
  margin: 0 auto 2rem;
`

const Button = styled.a`
  display: inline-block;
  background: #4f46e5;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  font-weight: 600;
  text-decoration: none;
  cursor: pointer;

  &:hover {
    background: #4338ca;
  }
`

export default function Home() {
  return (
    <Layout>
      <Hero>
        <Title>Your Data-Driven Sports Betting Edge</Title>
        <Subtitle>
          Unlock daily picks generated by our proprietary algorithm. Beat the books
          with smart, data-backed predictions.
        </Subtitle>
        {/* Use legacyBehavior so Link doesn’t wrap another <a> around Button */}
        <Link href="/register" passHref legacyBehavior>
          <Button>Get Started</Button>
        </Link>
      </Hero>
    </Layout>
  )
}
